version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/testdb
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network

  project-service:
    build: ./project-service
    ports:
      - "8081:8080" # Expose project service on port 8081
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/testdb
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network

  task-service:
    build: ./task-service
    ports:
      - "8082:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/testdb
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - user-service
      - project-service
      - task-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
