version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/testdb
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network
    volumes:
      - user-mongo_store:/data/db

  project-service:
    build: ./project-service
    ports:
      - "8081:8080"
    depends_on:
      - nats
      - mongo
      - user-service
    environment:
      - NATS_URL=${NATS_URL}
      - MONGO_URI=mongodb://mongo:27017/testdb
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network
    volumes:
      - project-mongo_store:/data/db

  task-service:
    build: ./task-service
    ports:
      - "8082:8080"
    depends_on:
      - mongo
      - nats
    environment:
      - NATS_URL=${NATS_URL}
      - MONGO_URI=mongodb://mongo:27017/testdb
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network
    volumes:
      - task-mongo_store:/data/db

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # NGINX konfiguracija
      - ./certs:/etc/nginx/certs            # Sertifikati se mapiraju u kontejner
    ports:
      - "443:443"                           # HTTPS port
      - "80:80"                             # HTTP port (za redirekciju ili unutrašnji saobraćaj)
    depends_on:
      - user-service
      - project-service
      - task-service
      - notification-service
    networks:
      - app-network
    environment:
      - NGINX_HOST=localhost               # Dodatno ako je potrebno za NGINX podešavanje

  notification-service:
    build: ./notification-service
    restart: always
    ports:
      - "8083:8080"
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=notifications
    depends_on:
      cassandra:
        condition: service_healthy
      nats:
        condition: service_started
    networks:
      - app-network
    volumes:
      - cass_store:/var/lib/cassandra/data


  cassandra:
    image: cassandra:4.0
    restart: always
    container_name: "cassandra"
    hostname: "cassandra"
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_LISTENER_RPC_ADDRESS=0.0.0.0
    healthcheck:
      test: ["CMD", "cqlsh", "--username", "cassandra", "--password", "cassandra", "--execute", "describe keyspaces"]
      interval: 15s
      retries: 5
      timeout: 15s
    volumes:
      - cass_store:/var/lib/cassandra
    networks:
      - app-network

  nats:
    image: 'nats:latest'
    expose:
      - ${NATS_PORT}
    ports:
      - ${NATS_PORTS}
    networks:
      - app-network

volumes:
  task-mongo_store:
  project-mongo_store:
  user-mongo_store:
  cass_store:

networks:
  app-network:
    driver: bridge
